services:
  api:
    image: airlock-api:dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${SCAN_UPLOAD_PATH}:/uploads
    env_file:
      - .env
    container_name: airlock-api
    environment:
      - PYTHONUNBUFFERED=1  # Forces immediate log flushing
      - LOG_LEVEL=DEBUG
      - PORT=${AIRLOCK_API_INTERNAL_PORT:-8000} # Pass the internal port to the container
      - SYFT_BINARY_PATH=/usr/local/bin/syft
    ports:
      # Format is EXTERNAL:INTERNAL
      - "${AIRLOCK_API_EXTERNAL_PORT:-8000}:${AIRLOCK_API_INTERNAL_PORT:-8000}"
    restart: always
